/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.vetelkedoController;
import java.awt.FlowLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.doorModel;

/**
 *
 * @author viczai.p.milan
 */
public class vetelkedoView extends javax.swing.JFrame {

    /**
     * Creates new form vetelkedoView
     */
    
    private vetelkedoController controller;
    private JLabel[] doorLabels = new JLabel[3];
    
    
    public vetelkedoView() {
        
        initComponents();
         controller = new vetelkedoController();
        setupUI();
    }
    
    
    private void setupUI() {
        setTitle("Monty Hall Játék");
        setSize(1000, 600);
        setLayout(new FlowLayout());

        doorModel[] ajtok = controller.getDoors();
        
        

        for (int i = 0; i < ajtok.length; i++) {
            doorModel ajto = ajtok[i];
            ImageIcon icon = new ImageIcon(ajto.getImagePath().toString());

            JLabel label = new JLabel(icon);
            
             //Kattintás esemény
            label.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    if (ajto.getPrize() == 1) {
                        label.setIcon(new ImageIcon("src/view/kepek/nyitottajto.png"));
                        JOptionPane.showMessageDialog(null, "🎉 Gratulálok, nyertél egy autót!");
                    } else {
                        label.setIcon(new ImageIcon("src/view/kepek/nyitottajto.png"));
                        JOptionPane.showMessageDialog(null, "😅 Ez most egy kecske volt!");
                    }
                }
            });

            doorLabels[i] = label;
            add(label);
        }

        setVisible(true);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        jMenuItem1.setText("ujJatek");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        setupUI();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
